# Base image
FROM node:16-alpine3.14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install TypeScript
RUN npm install -g typescript

# Install dependencies
RUN npm install

# Copy the rest of the client code
COPY . .

# Build the app
RUN npm run build

# Expose port 3000
EXPOSE 3000

# Start the app
CMD ["npm", "run", "dev"]