version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules 
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - db
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules 
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: