# Base image
FROM node:16-alpine3.14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install TypeScript
RUN npm install -g typescript

# Install dependencies
RUN npm install

# Copy the rest of the server code
COPY . .


# Build the app
RUN npx tsc
# RUN npm run build

# Expose port 8080
EXPOSE 8080

# Start the app
CMD ["npm", "run", "dev"]