# Base image
FROM node:16-alpine3.14

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install TypeScript
RUN npm install typescript

# # Install dependencies
RUN npm install

# Copy the rest of the server code
COPY . .

# # Debugging step
# RUN ls -al /app/dist

# Build the app
RUN npm run build

# Expose port 8080
EXPOSE 8080

# Start the app
CMD ["node", "dist/index.js"]