# Base image with Node.js 16 LTS
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

RUN apk --no-cache add --virtual .gyp python3 make g++

RUN npm rebuild bcrypt --build-from-source

# Install dependencies
RUN npm install

# Install TypeScript globally
RUN npm install -g typescript

# Copy the source code
COPY ./src ./src

# Build the app for production
RUN npm run build

# Expose port 8080
EXPOSE 8080

# Start the app
CMD ["npm", "run", "dev"]